#!/usr/bin/env python3
"""Append a v33e F3inv_Vsel coarse_cache_file_list block to a config template.

The v32x/v33f fitter already reads F3inv_Vsel merged caches.  The v33e
separated-component production directories also include F3inv_Vsel .bin + sidecar
files.  This helper finds the exact v33e files under V33E_CACHE_ROOT and writes a
runtime config with explicit paths, so the fitter never silently falls back to an
older cache.
"""
from __future__ import annotations
import argparse
from pathlib import Path
import sys

DEFAULT_IRREPS = ["000_A1m", "100_A2", "110_A2", "111_A2", "200_A2"]
DEFAULT_LS = [20, 24]

def xi_tag(x: str) -> str:
    return x.replace('.', 'p')

def find_one(root: Path, L: int, xi: str, irrep: str, coarseN: int) -> Path:
    fname = f"v32zu_Lbyas{L}_xi{xi_tag(xi)}_irrep{irrep}_coarse{coarseN}_F3inv_Vsel_gpu.bin"
    hits = sorted(root.rglob(fname))
    if not hits:
        raise FileNotFoundError(f"missing {fname} under {root}")
    if not (Path(str(hits[0]) + ".meta.json").exists()):
        raise FileNotFoundError(f"missing sidecar for {hits[0]}")
    return hits[0]

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--template", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--cache-root", required=True)
    ap.add_argument("--coarseN", type=int, default=20000)
    ap.add_argument("--xi", default="3.444")
    ap.add_argument("--Ls", nargs="*", type=int, default=DEFAULT_LS)
    ap.add_argument("--irreps", nargs="*", default=DEFAULT_IRREPS)
    args = ap.parse_args()

    root = Path(args.cache_root).expanduser().resolve()
    template = Path(args.template)
    out = Path(args.out)
    text = template.read_text()
    block = ["", "# --- explicit v33e F3inv_Vsel cache paths generated by scripts/make_v33e_cache_file_list.py ---", "coarse_cache_file_list"]
    for L in args.Ls:
        for irrep in args.irreps:
            path = find_one(root, L, args.xi, irrep, args.coarseN)
            block.append(f"{L} {irrep} {path}")
    block.append("end_coarse_cache_file_list")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text.rstrip() + "\n" + "\n".join(block) + "\n")
    print(f"[v33f-cache-list] wrote {out}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
